### ISSUE TITLE
glibc version is too new for some Linux distribution

### ISSUE THREAD

**Issue by ImpleLee** [26F-Studio/cold_clear_ai_love2d_wrapper#23]
![Screenshot 2023-02-14 1 52 32 AM](https://user-images.githubusercontent.com/51223488/218701119-d65f31d9-9adc-4284-9c1c-5d29c5043914.png)

_Originally posted by @AlphaIru in https://github.com/26F-Studio/Techmino/issues/851#issuecomment-1429448951_

**Comment by shoucandanghehe** [comment]
![image](https://user-images.githubusercontent.com/51957264/219809100-b5363edd-ed62-4768-a2e2-b54dd78c9d68.png)
![image](https://user-images.githubusercontent.com/51957264/219809288-579e201c-389b-4014-93d1-36dd64913241.png)

same issue on Ubuntu18.04 and Debian11
